### ISSUE TITLE
Preventing Fake Payment Requests

### ISSUE THREAD

**Issue by Zhongyi-Lu** [Privacy-and-Security/AuthGate_Server#1]
Hi,

It's been observed that our backend is vulnerable to **spoofed payment requests**, leading to potential payment security issues.

Can we address this by adding verification layers, such as API key checks or HMAC signatures?

**Comment by Yuyan-Lei** [comment]
Solved by adding reCatpcha validation on the server side. Thanks.

**Comment by Yuyan-Lei** [comment]
Solved by adding reCaptcha validation on the server side. Thanks.

**Comment by Yuyan-Lei** [comment]
Solved by adding reCaptcha validation on the server side. Thanks.
